REVOKE EXECUTE ON FUNCTION public.activate_school_subscription(_school_id uuid, _new_end_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.activate_school_subscription(_school_id uuid, _new_end_date date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_approve_gestor_trial(_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.admin_approve_gestor_trial(_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_log_profile_deletion(_profile_id uuid, _user_id uuid, _full_name text, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.admin_log_profile_deletion(_profile_id uuid, _user_id uuid, _full_name text, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_profile_access(_profile_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.admin_revoke_profile_access(_profile_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_unlink_self_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.admin_unlink_self_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.approve_school_transfer(_request_id uuid, _note text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.approve_school_transfer(_request_id uuid, _note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.broadcast_app_refresh() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.broadcast_app_refresh() FROM anon;
REVOKE EXECUTE ON FUNCTION public.bulk_set_schools_status(_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.bulk_set_schools_status(_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_health_checks() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.cleanup_old_health_checks() FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_old_linter_reports() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.cleanup_old_linter_reports() FROM anon;
REVOKE EXECUTE ON FUNCTION public.ensure_admin_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.ensure_admin_profile() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_admin_dashboard_counts() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_admin_dashboard_counts() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_mp_force_test_mode() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_mp_force_test_mode() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_assinatura() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_my_assinatura() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_latest_decision() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_my_latest_decision() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_subscription_deadline() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_my_subscription_deadline() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_my_trial_status() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_my_trial_status() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_plan_migration_quote(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_plan_migration_quote(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_school_access_info(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_school_access_info(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_school_access_level(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_school_access_level(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_school_subscription_admin(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_school_subscription_admin(_school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_school_id(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.get_user_school_id(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.has_role(_user_id uuid, _role app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_chef_of_school(_user_id uuid, _school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.is_chef_of_school(_user_id uuid, _school_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_user_approved(_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.is_user_approved(_uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_expiring_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_expiring_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_prospect_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_prospect_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_school_cities_admin(_state text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_school_cities_admin(_state text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_school_states_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_school_states_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_schools_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_schools_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_schools_admin_paginated(_state text, _city text, _network text, _search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_schools_admin_paginated(_state text, _city text, _network text, _search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_schools_deadlines_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_schools_deadlines_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_schools_simple(_search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_schools_simple(_search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_schools_simple_filtered(_state text, _city text, _network text, _search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_schools_simple_filtered(_state text, _city text, _network text, _search text, _limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_subscribed_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_subscribed_schools_admin(_limit integer, _offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.list_subscription_notifications_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.list_subscription_notifications_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.manager_decide_profile(_profile_id uuid, _decision text, _reason text, _approve_as_intended boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.manager_decide_profile(_profile_id uuid, _decision text, _reason text, _approve_as_intended boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_school_gestores_communique(_school_id uuid, _author_name text, _author_role text, _booking_id uuid, _summary text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.notify_school_gestores_communique(_school_id uuid, _author_name text, _author_role text, _booking_id uuid, _summary text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.preview_bulk_set_schools_status(_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.preview_bulk_set_schools_status(_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.reject_school_transfer(_request_id uuid, _note text) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.reject_school_transfer(_request_id uuid, _note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_minimum_supported_version(_version text, _build_time bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.set_minimum_supported_version(_version text, _build_time bigint) FROM anon;
REVOKE EXECUTE ON FUNCTION public.set_mp_force_test_mode(_enabled boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.set_mp_force_test_mode(_enabled boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.sync_gestor_subscription_deadlines() FROM anon;
REVOKE EXECUTE ON FUNCTION private_api.sync_gestor_subscription_deadlines() FROM anon;