INSERT INTO public.schools (name, city, state, network) VALUES
('Centro Especializado Em Transtorno do Espectro Autista da Rede Municipal de Ensino', 'Boa Vista', 'RR', 'municipal'),
('Centro Municipal Integrado de Educação Especial', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Aldo Torreias do Nascimento', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Alirio Santos Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ana Sandra Nascimento Queiroz', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Antonia Fernandes Cutrin', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Antonio Carlos Magalhaes', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Aquilino da Mota Duarte', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Arco-iris', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Balduino Wottrich', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Barao do Rio Branco', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Branca de Neve', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Brilho do Sol', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Caetano Jose de Sousa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Cantinho Feliz', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Cantinho do Ceu', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Casinha Feliz', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Centenario de Boa Vista', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Colibri', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Complexo Educacional Jael Ferreira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Creche Proinfancia Professora Lidia Coelho Tavares', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Criança Feliz', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Cunhata Curumim', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Dalicio Faria Filho', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Elcione Tereza de Oliveira Barbalho', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Eurides da Cunha Brasil', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Firmino Barbosa Ribeiro', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Francisco de Souza Briglia', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Getulio Vargas', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Avelino Lopes da Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Lino de Souza', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Luiza Wapixana', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Maria Raposa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Severino Soares de Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Albino Moraes', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Antonio Horacio', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Manoel Flores', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Pedro Augustinho', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Salvador Ventura', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Tuxaua Silvestre Messias', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Ind Zenilda Lopes', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Indígena Dukuzyy Sebastiao', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Indígena Ignes Benedicto', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Indígena Vicente Andre da Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Indígena Vovo Antonia Celestina da Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Irineu da Gama Paim', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Janio da Silva Quadros', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Jardim Floresta', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Jesus de Nazare', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Jose Anselmo de Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Jose Vieira de Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Jurandir de Araujo', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Lourenço Borges Dias', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Luana Vitoria Pereira da Costa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Luiz Canara', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Manoel Bandeira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Marechal Candido Rondon', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Maria Gloria de Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Maria Teresa de Jesus Barbosa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Maria das Neves Rezende', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Maria dos Navegantes Paiva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Martinha Thury Vieira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Menino Jesus', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Monteiro Lobato', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Morel Furtado', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Nair Maciel Marques', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Nenzinha Vieira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Nossa Senhora de Nazare', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Nova Canaa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Olivio Gomes da Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Padre Anchieta', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Patricia Rocha Pereira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Paulo Sérgio Frutuoso Guimarães', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Pedro Elias Dibo', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Pedro Justino Guedes', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Pequeno Polegar', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Pingo de Gente', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Presidente Costa e Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Presidente Juscelino Kubitschek', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Prof Jose Geraldo Rodrigues Alves', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Prof Rinaldo Vaz de Lima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profa Ana Liboria', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profa Conceicao da Costa e Silva', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profa Laucides Inacio de Oliveira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profa Severina Bezerra de Melo', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profesora Edsonina de Barros Villa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Profª Carmem Eugenia Macaggi', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Raimundo Elias Ximenes', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Raimundo Nonato Nogueira Cesar', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Raio de Luz', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Roraima', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Rosalva Nunes de Oliveira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Rujane Severiano dos Santos', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Sebastiana de Jesus Almeida', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Severino Goncalves Cavalcante', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Tereza Amelia Rodrigues', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Valdemarina Normando Martins', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Vitoria Mota da Costa', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal Vovo Nenzinha', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Casa Mae Senador II', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Antonio Airton Oliveira Dias', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Arco-Iris', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Cantinho do Amor', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Asa Branca', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Bela Vista', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Buritis', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Caimbe', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Calunga', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Carana', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Centenario', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Doutor Silvio Leite', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Equatorial', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Flor do Campo', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Joquei Clube', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Lagoa Encantada', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Laura Moreira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Liberdade', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Luz do Sol', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Mecejana', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Mundo Encantado', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Nova Cidade', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Pedacinho de Gente', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Pintolandia', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Priscila Mirian Galvao Almeida', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Raiar do Sol', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Recanto do Amor', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Santa Luzia', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Senador I', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Sinha Laranjeira', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Tancredo Neves', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Casa Mae Tia Aurea', 'Boa Vista', 'RR', 'municipal'),
('Escola Municipal de Educação Infantil Crianca Esperanca', 'Boa Vista', 'RR', 'municipal');